export const samples = [
  "/images/samples/1.jpg",
  "/images/samples/2.jpg",
  "/images/samples/3.jpg",
  "/images/samples/4.jpg",
  "/images/samples/5.jpg",
  "/images/samples/6.jpg",
  "/images/samples/7.jpg",
  "/images/samples/8.jpg",
];

export const samplesGallery = [
  "/images/samples/1.jpg",
  "/images/samples/2.jpg",
  "/images/samples/3.jpg",
  "/images/samples/4.jpg",
  "/images/samples/5.jpg",
  "/images/samples/6.jpg",
  "/images/samples/7.jpg",
  "/images/samples/8.jpg",
  "/images/samples/9.jpg",
  "/images/samples/10.jpg",
  "/images/samples/11.jpg",
  "/images/samples/12.jpg",
  "/images/samples/13.jpg",
  "/images/samples/14.jpg",
  "/images/samples/15.jpg",
  "/images/samples/16.jpg",
  "/images/samples/17.jpg",
  "/images/samples/18.jpg",
  "/images/samples/19.jpg",
  "/images/samples/20.jpg",
  "/images/samples/21.jpg",
  "/images/samples/22.jpg",
  "/images/samples/23.jpg",
  "/images/samples/24.jpg",
];
